enableGlobalVirtualStore: false

overrides:
  "@babel/runtime": 7.29.7
  glob: 10.5.0
  js-yaml: 3.15.1
  mdast-util-to-hast: 13.2.1
  micromatch: 4.0.8
  minimatch: 9.0.7
  picomatch: 2.3.2
  unified: 11.0.5
  yaml: 2.8.3
